name: Devops First Pipeline

on:
  push:
    branches:
      - main 

jobs: 
  integration: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Building the app
        run: | 
          dotnet build ConsoleApp/
      
      - name: Collect executables 
        uses: actions/upload-artifact@v4
        with: 
          name: executables
          path: ConsoleApp/bin
      